require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/*
    - vendor/**/*
  TargetRubyVersion: '3.3'
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'
    - spec/**/*
    - config/environments/**/*
    - config/routes.rb

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'db/migrate/**'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 45
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 1000

Metrics/ClassLength:
  Max: 1000

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 25

RSpec/ExampleLength:
  Max: 500

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/AnyInstance:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/Output:
  Enabled: false
